[versions]
accompanistPermissions = "0.37.3"
activityCompose = "1.12.0"
agp = "8.13.1"
androidTools = "31.13.1"
composeBom = "2025.11.01"
coreKtx = "1.17.0"
coreTesting = "2.2.0"
detektPlugin = "1.23.8"
espressoCore = "3.7.0"
hilt = "2.57.2"
hiltNavigationCompose = "1.3.0"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.21"
kotlinxCoroutines = "1.10.2"
kotlinxCoroutinesTest = "1.10.2"
kotlinxSerializationJson = "1.9.0"
ksp = "2.3.2"
lifecycleRuntimeKtx = "2.10.0"
lifecycleViewmodelNav3 = "2.10.0"
mockitoCore = "5.20.0"
mockitoKotlin = "6.1.0"
mockitoAndroid = "5.20.0"
nav3Core = "1.0.0"
timber = "5.0.1"
appcompat = "1.7.1"
robolectric = "4.16"
striktCore = "0.35.1"
treessence = "1.1.2"
turbine = "1.2.1"
material = "1.13.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "junitVersion" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoAndroid" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
strikt-core = { module = "io.strikt:strikt-core", version.ref = "striktCore" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
treessence = { group = "com.github.bastienpaulfr", name = "Treessence", version.ref = "treessence" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

# Dependencies of the included build-logic
android-gradleApiPlugin = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
detekt-gradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detektPlugin" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektPlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

connectivity-samples-android-library = { id = "connectivity.samples.android.library" }
connectivity-samples-android-library-compose = { id = "connectivity.samples.android.library.compose" }
connectivity-samples-android-feature = { id = "connectivity.samples.android.feature" }
connectivity-samples-hilt = { id = "connectivity.samples.hilt" }
connectivity-samples-jvm-library = { id = "connectivity.samples.jvm.library" }
connectivity-samples-lint = { id = "connectivity.samples.lint" }
connectivity-samples-root = { id = "connectivity.samples.root" }

